In [3]:
#load libraries
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [5]:
setwd("/home/user/Capstone/data_center_research")

In [6]:
#Import CSV file on data centers in Virginia
data_centers <- read.csv("data/raw_data/pec_data_centers.csv")

In [7]:
#show first 10 rows
head(data_centers, 10)

   OBJECTID PEC_ID                    Locality
1   1       PEC-CAR-0001/PEC-SPO-0003 Caroline County
2   2       PEC-CAR-0002              Caroline County
3   3       PEC-CAR-0003              Caroline County
4   4       PEC-CHE-0001              Chesterfield County
5   5       PEC-CHE-0002              Chesterfield County
6   6       PEC-CUL-0001              Culpeper County
7   7       PEC-CUL-0002              Culpeper County
8   8       PEC-CUL-0003              Culpeper County
9   9       PEC-CUL-0004              Culpeper County
10 10       PEC-CUL-0005              Culpeper County
   Name                                     Owner_Applicant
1  Mattameade Tech Campus                   Amazon Data Services Inc
2  VALCO Data Center Park                   VALCO CAROLINE COUNTY
3  Carmel Church Data Hub                   W & F PARTNERS
4  Digital Fortress: Richmond               CHIRISA RICHMOND LLC
5  Virginia Information Technologies Agency SLK GLOBAL SOLUTIONS AMERICA
6  Equinix                                  EQUINIX
7  SWIFT                                    SWIFT
8  Cielo Digital Infrastructure             Edgecore
9  CloudHQ                                  CloudHQ
10 Copper Ridge                             STACK INFRASTRUCTURE
   Street_Address                                      Parcel_ID       Acres
1  Stonewall Jackson Road just east of the Mudd Tavern 27-A-4A         916.07
2  Mt Airy Road                                        80-A-43         855.00
3  Welcom Way Dr                                       82-14-A          97.00
4  1401 MEADOWVILLE TECH PARKWAY                       823657720300000  74.80
5  11751 MEADOWVILLE LANE                              822656429800000  28.14
6    18155 TECHNOLOGY DR                               51-83A1          30.12
7                                                      51       83F        NA
8  Cielo Digital Infrastructure                        41-110          120.89
9  14521 MCDEVITT DR                                   41-106D          98.56
10                                                                         NA
   Building_Sq_Ft MW_reported ⋯ Build_Status
1  4,500,000      NA          ⋯ Proposed
2  1,216,000      NA          ⋯ Proposed
3  1,600,000      NA          ⋯ Proposed
4  242,042        25          ⋯ Existing
5  192,195        NA          ⋯ Existing
6  370,000        NA          ⋯ Existing
7  90,000         NA          ⋯ Existing
8  1,400,000      NA          ⋯ Proposed
9  2,100,000      NA          ⋯ Proposed
10 2,200,000      NA          ⋯ Proposed
   Notes
1  Sister property to Spotsylvania campus- represents total square footage
2  Project covers more than one parcel, the acreage represents the combined acreage
3  Project covers more than one parcel, the acreage represents the combined acreage
4  Formerly a Capital One data center - vacated and for sale
5
6
7
8  Project covers more than one parcel, the acreage represents the combined acreage
9  Project covers more than one parcel, the acreage represents the combined acreage
10
   Tax_Map_link
1
2
3
4  https://www.chesterfield.gov/828/Real-Estate-Assessment-Data#/Details/823657720300000
5  https://www.chesterfield.gov/828/Real-Estate-Assessment-Data#/Details/822656429800000
6  https://gis.vgsi.com/culpeperva/Parcel.aspx?pid=10680
7
8  https://gis.vgsi.com/culpeperva/Parcel.aspx?pid=3148
9  https://gis.vgsi.com/culpeperva/Parcel.aspx?pid=21853
10
   Source_link
1  https://co.caroline.va.us/DocumentCenter/View/7255/RZ-02-2023-Orrock-Tech-Camus?bidId=
2  https://co.caroline.va.us/AgendaCenter/ViewFile/Item/5593?fileID=9447
3  https://co.caroline.va.us/DocumentCenter/View/9366/RZ-03-2023--Carmel-Church-Data-Hub
4
5
6
7
8  http://go.boarddocs.com/va/ccva/Board.nsf/goto?open&id=CWBKLL525B17
9  https://www.culpeperva.org/properties/cloudhq-culpeper/#:~:text=CloudHQ%2C%20a%20global%20data%20center,of%20critical%20IT%20load%20power.
10 https://datacenterdynamics.com/en/news/amazon-granted-rezoning-approval-for-data-centers-in-culpeper-county-virginia/
   Lat      Long      Date_Updated Updated_By Lat1     Watershed
1  38.11465 -77.49115 2024-04-10   SEP        38.11465 NA
2  37.92410 -77.54387 2024-04-10   SEP        37.92410 NA
3  37.93933 -77.47797 2024-04-10   SEP        37.93933 NA
4  37.36048 -77.32741 2024-04-10   SEP        37.36048 NA
5  37.36041 -77.33178 2024-04-10   SEP        37.36041 NA
6  38.45494 -77.97828 2024-04-10   SEP        38.45494 NA
7  38.45554 -77.98348 2024-04-10   SEP        38.45554 NA
8  38.46679 -77.96353 2024-04-10   SEP        38.46679 NA
9  38.46164 -77.97762 2024-04-10   SEP        38.46164 NA
10 38.46529 -77.98739 2024-04-10   SEP        38.46529 NA

In [8]:
#Create new dataframe
data_centers_clean <- as.data.frame(data_centers)

In [9]:
#Rename variables
data_centers_clean <- data_centers_clean %>%
  rename(
    object_id = OBJECTID,
    locality = Locality,
    name = Name,
    owner_applicant = Owner_Applicant,
    street_address = Street_Address,
    construction_type = Construction_Type,
    build_status = Build_Status,
    lat = Lat,
    long = Long,
  )

In [10]:
# Examine rows with missing longitude and latitude coordinates, blank space after the comma means "keep all columns"

data_centers_clean[is.na(data_centers_clean$long) | is.na(data_centers_clean$lat), ]

    object_id PEC_ID        locality       name
394 458       PEC-LDN-0132A Loudoun County PROJECT ASPEN
406 475       PEC-LDN-0157  Loudoun County MERCURE BUSINESS PARK LOT 22
    owner_applicant         street_address               Parcel_ID    Acres
394 HAYDEN TECHNOLOGIES LLC 20491 GOOSE LANDING LN       194498227000 0.00
406 L22 LLC/ John Cox       44211 MERCURE CIR , STERLING 091493983000 5.49
    Building_Sq_Ft MW_reported ⋯ build_status
394 324890         NA          ⋯ Proposed
406 95,658         NA          ⋯ Proposed
    Notes
394
406 Currently flex warehouse. Current building completed in 2022
    Tax_Map_link
394 https://reparcelasmt.loudoun.gov/pt/Datalets/Datalet.aspx?UseSearch=no&mode=profileall&pin=194498227000&jur=107&taxyr=2024
406 https://reparcelasmt.loudoun.gov/pt/Datalets/Datalet.aspx?UseSearch=no&mode=profileall&pin=091493983000&jur=107&taxyr=2025
    Source_link
394 https://loudouncountyvaeg.tylerhost.net/prod/selfservice#/plan/e48043e8-fdbb-4e91-aa87-60d35cb71173?tab=attachments
406 https://loudouncountyvaeg.tylerhost.net/prod/selfservice#/plan/a037a799-691c-42c4-a3fa-dd41c9dfa911?tab=attachments
    lat long      Date_Updated Updated_By Lat1 Watershed
394 NA  -77.53495 2025-08-11   SEP        NA   NA
406 NA         NA 2025-10-17   SEP        NA   NA

In [11]:
# Keep rows where long and lat exists

data_centers_clean <- data_centers_clean %>%
  filter(!is.na(long) & !is.na(lat))


# Can disregard #399 and #411 as they are proposed and we only want existing data centers; will filter for existing data centers next

In [12]:
#Select only relevant columns and rows
data_centers_clean <- data_centers_clean %>%
    select(object_id, locality, name, street_address, owner_applicant, construction_type, build_status,lat, long) %>%
    filter(locality == "Loudoun County")%>% # keep only Loudoun County rows
    filter(build_status == "Existing")   # keep only Existing rows

In [13]:
write.csv(
  data_centers_clean,
  "/home/user/Capstone/data_center_research/data/processed/data_centers_clean.csv",
  row.names = FALSE
)